"""add delivery_config table

Revision ID: 11351
Revises: f1a2b3c4d5e6
Create Date: 2026-08-19 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11351"
down_revision = "f1a2b3c4d5e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fee_amount", sa.DECIMAL(10, 2), nullable=False, server_default="0.00"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()"), onupdate=sa.text("now")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Insert default configuration row (fee = 0.00, active)
    op.execute("INSERT INTO delivery_config (fee_amount, is_active) VALUES (0.00, 1)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery_config")
    # ### end Alembic commands ###